### ISSUE TITLE
希望提供除 Country.mmdb 和 IP-CIDR 段的其他支持

### ISSUE THREAD

**Issue by chenyiping1995** [Hackl0us/GeoIP2-CN#7]
由于 Clash 的 Country.mmdb 并不能实现自动更新,只能手动替换;而geoip-cn.txt 又不被大部分软件直接接受,因此能否烦请作者同时提供以下格式的内容?

在此先谢过先!

## Clash Rule-Provider YAML

Clash Rule-Provider 文档: https://lancellc.gitbook.io/clash/clash-config-file/rule-provider#example-of-a-rule-provider-file
样例文件：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIp.yaml
使用方法：
```yaml
rule-providers:
  ChinaIP:
    type: http
    behavior: ipcidr
    path: ./profiles/rule-providers/ChinaIp.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIp.yaml #由于Clash不支持通过代理更新，需要做镜像/CDN
    interval: 86400

rules:
  - RULE-SET,ChinaIP,DIRECT
```

## Quantumult X Remote Filter / Clash 配置片段
样例文件：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
使用方法：
```ini
[filter_remote]
https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list, tag=国内 IP 段, force-policy=DIRECT, update-interval=86400, opt-parser=true, enabled=true
```

## Surge Rule Set
样例文件：https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/ChinaIP.list
使用方法：
```ini
[Rule]
RULE-SET,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/ChinaIP.list,DIRECT
```
